# Generated by Django 4.2.4 on 2024-09-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_landpage",
            field=models.BooleanField(default=False),
        ),
    ]
