# Generated by Django 4.2.4 on 2024-09-28 15:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="benfitssection",
            name="description_ar",
            field=models.TextField(default=1, verbose_name="Arabic Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="benfitssection",
            name="title_ar",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Arabic title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursessection",
            name="description_ar",
            field=models.TextField(default=1, verbose_name="Arabic Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursessection",
            name="title_ar",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Arabic title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainsection",
            name="description_ar",
            field=models.TextField(default=1, verbose_name="Arabic Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainsection",
            name="title_ar",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Arabic title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="features_ar",
            field=ckeditor.fields.RichTextField(
                default=1, verbose_name="Arabic Features"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="plan_ar",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Arabic Plan name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userlandingpage",
            name="description_ar",
            field=models.TextField(default=1, verbose_name="Arabic description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userlandingpage",
            name="title_ar",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Arabic title"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pricing",
            name="plan",
            field=models.CharField(max_length=100, verbose_name="Plan Name"),
        ),
    ]
