# Generated by Django 4.2.4 on 2024-09-28 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0003_mainlandingpage_benfits_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlandingpage",
            old_name="url",
            new_name="pagename",
        ),
    ]
