# Generated by Django 4.2.4 on 2024-09-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0006_alter_userrequested_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/landing_page/image"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("link", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="mainlandingpage",
            name="social_medias",
            field=models.ManyToManyField(
                related_name="landing_pages", to="landing_page.socialmedia"
            ),
        ),
    ]
