# Generated by Django 4.2.4 on 2024-09-30 16:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0007_socialmedia_mainlandingpage_social_medias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricing",
            options={
                "verbose_name": "User's opinion",
                "verbose_name_plural": "Users' opinions",
            },
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="plan_ar",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="price",
        ),
        migrations.AddField(
            model_name="pricing",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/landing_page/image"
            ),
        ),
        migrations.AddField(
            model_name="pricing",
            name="name",
            field=models.CharField(default=1, max_length=100, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="name_ar",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Arabic name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mainlandingpage",
            name="pricing_plans",
            field=models.ManyToManyField(
                related_name="landing_pages",
                to="landing_page.pricing",
                verbose_name="Users opinions",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="features",
            field=ckeditor.fields.RichTextField(verbose_name="opinions"),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="features_ar",
            field=ckeditor.fields.RichTextField(verbose_name="Arabic opinions"),
        ),
    ]
