# Generated by Django 4.2.4 on 2024-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0008_alter_pricing_options_remove_pricing_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricing",
            name="features",
            field=models.TextField(verbose_name="opinions"),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="features_ar",
            field=models.TextField(verbose_name="Arabic opinions"),
        ),
    ]
