# Generated by Django 4.2.4 on 2024-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0009_alter_pricing_features_alter_pricing_features_ar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video_message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=100)),
                (
                    "message_ar",
                    models.CharField(max_length=100, verbose_name="Arabic message"),
                ),
            ],
        ),
    ]
