# Generated by Django 4.2.4 on 2025-03-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "landing_page",
            "0011_userrequested_conected_userrequested_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="static/landing_page/video"
            ),
        ),
    ]
