# Generated by Django 4.2.4 on 2025-03-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0012_pricing_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursessection",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="static/landing_page/video"
            ),
        ),
    ]
