# Generated by Django 4.2.4 on 2025-03-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_page", "0013_coursessection_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursessection",
            name="video_poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/landing_page/image"
            ),
        ),
        migrations.AddField(
            model_name="pricing",
            name="terabox_url",
            field=models.URLField(blank=True, null=True, verbose_name="Terabox URL"),
        ),
        migrations.AddField(
            model_name="pricing",
            name="video_poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/landing_page/image"
            ),
        ),
    ]
