# Generated by Django 4.2.4 on 2025-04-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "landing_page",
            "0014_coursessection_video_poster_pricing_terabox_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlandingpage",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userlandingpage",
            name="title_ar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Arabic title"
            ),
        ),
    ]
