# Generated by Django 4.2.4 on 2024-09-06 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marketing_Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/course/image")),
                ("title", models.CharField(max_length=100)),
                ("rate", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Marketing_Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="static/course/image")),
                ("description", models.TextField(blank=True, null=True)),
                ("video", models.FileField(upload_to="static/course/video")),
                ("number", models.IntegerField(default=0)),
                ("rate", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Marketing_Lecture_rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.IntegerField(default=0)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketing.marketing_lecture",
                    ),
                ),
            ],
        ),
    ]
