# Generated by Django 4.2.4 on 2024-09-06 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("renewal_days", models.IntegerField(default=30)),
                ("isactive", models.BooleanField(default=False)),
                ("duration", models.IntegerField(default=90)),
                ("ishidden", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("birth_date", models.CharField(blank=True, max_length=100, null=True)),
                ("coin", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="static/users/"),
                ),
                ("price", models.FloatField(default=0)),
                ("marketing_avilable", models.BooleanField(default=False)),
                ("rank", models.IntegerField(default=0)),
                ("number", models.IntegerField(default=0)),
                ("no_time", models.BooleanField(default=False)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
