# Generated by Django 4.2.4 on 2025-02-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="name_ar",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
