# Generated by Django 4.2.4 on 2024-09-06 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture_rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ViewCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ViewLecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="lecture",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="rating_count",
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="url",
        ),
        migrations.AddField(
            model_name="course",
            name="member_ship",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.membership",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="course",
            name="rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="CourseRating",
        ),
        migrations.AddField(
            model_name="viewlecture",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.lecture"
            ),
        ),
    ]
