# Generated by Django 4.2.4 on 2024-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="reset_password_message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(max_length=100, verbose_name="English message"),
                ),
                (
                    "message_ar",
                    models.CharField(max_length=100, verbose_name="Arabic message"),
                ),
            ],
        ),
    ]
