# Generated by Django 4.2.4 on 2024-10-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_viewlecture_user_viewcourse_course_viewcourse_user_and_more"),
        ("home", "0002_reset_password_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(max_length=100, verbose_name="English message"),
                ),
                (
                    "message_ar",
                    models.CharField(max_length=100, verbose_name="Arabic message"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
    ]
