# Generated by Django 4.2.4 on 2024-10-06 20:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_coursemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemessage",
            name="message",
            field=ckeditor.fields.RichTextField(verbose_name="English message"),
        ),
        migrations.AlterField(
            model_name="coursemessage",
            name="message_ar",
            field=ckeditor.fields.RichTextField(verbose_name="Arabic message"),
        ),
        migrations.AlterField(
            model_name="reset_password_message",
            name="message",
            field=ckeditor.fields.RichTextField(verbose_name="English message"),
        ),
        migrations.AlterField(
            model_name="reset_password_message",
            name="message_ar",
            field=ckeditor.fields.RichTextField(verbose_name="Arabic message"),
        ),
        migrations.AlterField(
            model_name="wellcome_message",
            name="message",
            field=ckeditor.fields.RichTextField(verbose_name="English message"),
        ),
        migrations.AlterField(
            model_name="wellcome_message",
            name="message_ar",
            field=ckeditor.fields.RichTextField(verbose_name="Arabic message"),
        ),
    ]
